#
# Use with nmake
#
all:    bin/mhs.exe bin/mhseval.exe bin/libmhsi.dll

# Compile mhs from distribution, with C compiler
bin/mhs.exe:	src/runtime/*.c  src/runtime/windows/* #generated/mhs.c
	@-mkdir bin
	@-mkdir build
	cl -Fobuild\ -O2 -Isrc/runtime -Isrc/runtime/windows -Iinclude src/runtime/main.c src/runtime/eval.c generated/mhs.c -Febin/mhs.exe

# Compile combinator evaluator
bin/mhseval.exe:	src/runtime/*.c src/runtime/windows/* src/runtime/comb.c
	@-mkdir bin
	@-mkdir build
	cl -Fobuild\ -O2 -Isrc/runtime -Isrc/runtime/windows -Iinclude src/runtime/main.c src/runtime/eval.c src/runtime/comb.c -Febin/mhseval.exe

# Build the embeddable runtime as a DLL
bin/libmhsi.dll:	src/runtime/*.c src/runtime/windows/* generated/mhs.c
	@-mkdir bin
	@-mkdir build
	cl -Fobuild\ -O2 -Isrc/runtime -Isrc/runtime/windows -Iinclude -LD \
		src/runtime/mhseval.c src/runtime/libmhsi.c -link -OUT:bin/libmhsi.dll

exampletest:	bin/mhs.exe bin/mhseval.exe Example.hs
	bin\mhs -r Example
	bin\mhs Example && bin\mhseval
        bin\mhs -itests Nfib && bin\mhseval
	bin\mhs -r -itests Info
	bin\mhs -twindows Example -oEx.exe && Ex && rm Ex.exe
